### ISSUE TITLE
Add `CITATION.cff` Citation File Format file to repo

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1541]
# Description

@lukasheinrich @kratsg GitHub now will [add a citation button to repositories that have a Citation File Format file (`CITATION.cff`) on the default branch](https://twitter.com/natfriedman/status/1420122675813441540). This seems pretty good in general for citation of software. Also [Zenodo has now added support for `CITATION.cff` for linked GitHub repositories](https://twitter.com/ZENODO_ORG/status/1420357001490706442), which means that we can probably deprecate our `.zenodo.json` in favor of a `CITATION.cff`.

However, it seems that it is now a smooth replacement in all areas, especially as `pyhf` is trying to be careful about how people cite the software so that we get consistent citations and that people cite the JOSS paper [![DOI](https://joss.theoj.org/papers/10.21105/joss.02823/status.svg)](https://doi.org/10.21105/joss.02823) at the same time.

On my fork of `pyhf` I've been playing around with [the CFF file format](https://github.com/citation-file-format/citation-file-format/blob/main/README.md#file-structure) and the following

```yaml
cff-version: 1.1.0
message: "Please cite the following works when using this software."
type: software
authors:
- family-names: "Heinrich"
  given-names: "Lukas"
  orcid: "https://orcid.org/0000-0002-4048-7584"
- family-names: "Feickert"
  given-names: "Matthew"
  orcid: "https://orcid.org/0000-0003-4124-7862"
- family-names: "Stark"
  given-names: "Giordon"
  orcid: "https://orcid.org/0000-0001-6616-3433"
title: "scikit-hep/pyhf: v0.6.2"
version: 0.6.2
doi: 10.5281/zenodo.1169739
repository-code: "https://github.com/scikit-hep/pyhf"
url: "https://pyhf.readthedocs.io/en/v0.6.2/"
keywords:
  - python
  - physics
  - statistics
  - fitting
  - scipy
  - numpy
  - tensorflow
  - pytorch
  - jax
  - auto-differentiation
license: "Apache-2.0"
references:
  - type: article
    authors:
    - family-names: "Heinrich"
      given-names: "Lukas"
      orcid: "https://orcid.org/0000-0002-4048-7584"
    - family-names: "Feickert"
      given-names: "Matthew"
      orcid: "https://orcid.org/0000-0003-4124-7862"
    - family-names: "Stark"
      given-names: "Giordon"
      orcid: "https://orcid.org/0000-0001-6616-3433"
    - family-names: "Cranmer"
      given-names: "Kyle"
      orcid: "https://orcid.org/0000-0002-5769-7094"
    title: "pyhf: pure-Python implementation of HistFactory statistical models"
    doi: 10.21105/joss.02823
    url: "https://doi.org/10.21105/joss.02823"
    year: 2021
    publisher: The Open Journal
    volume: 6
    number: 58
    pages: 2823
    journal: Journal of Open Source Software
```

produces a window like (notice that the `message` seems to get overwritten by GitHub)

![example_box](https://user-images.githubusercontent.com/5142394/127754531-913beb0b-c123-4884-8926-457d76a51ec4.png)

and the copied citation gives

```
@misc{Heinrich_scikitheppyhf_v0.6.2_2021,
author = {Heinrich, Lukas and Feickert, Matthew and Stark, Giordon},
doi = {10.5281/zenodo.1169739},
month = {6},
title = {scikit-hep/pyhf: v0.6.2},
url = {https://github.com/scikit-hep/pyhf},
year = {2021}
}
```

which is a bit different from our preferred citation (of just the software) of

https://github.com/scikit-hep/pyhf/blob/8f35b102b47738fcda12c1fed30673abaa23ec68/src/pyhf/data/citation.bib#L1-L8

and doesn't get the reference citation for the JOSS paper

https://github.com/scikit-hep/pyhf/blob/8f35b102b47738fcda12c1fed30673abaa23ec68/src/pyhf/data/citation.bib#L10-L21

at all.

There's also no `CFF` validator that I know of as well that will check that everything is valid. Given that we've got our [`.zenodo.json`](https://github.com/scikit-hep/pyhf/blob/8f35b102b47738fcda12c1fed30673abaa23ec68/.zenodo.json) config file setup so that we know that it works (thanks to help from @lnielsen) we should be careful to not break Zenodo with this new format.

## Example libraries that are using the `CITATION.cff` now

- [Parsl](https://github.com/Parsl/parsl) (c.f. https://github.com/Parsl/parsl/pull/2100)

## Similar ongoing discussion on the topic

- https://github.com/scikit-hep/awkward-1.0/issues/1034

cc @danielskatz @cranmer

## Other related references

- [Citation File Format website](https://citation-file-format.github.io/)
- [Citation File Format repo](https://github.com/citation-file-format/citation-file-format)
- [GitHub Docs: About CITATION files](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files)
   - Unfortunately, GitHub is currently showing a `cff-version: 1.2.0` that is invalid, as the latest [CFF release is `1.1.0`](https://github.com/citation-file-format/citation-file-format/releases/tag/1.1.0)
