### ISSUE TITLE
Add test against release candidates on PyPI to HEAD of dependencies workflow

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1659]
### Summary

The [HEAD of dependencies workflow](https://github.com/scikit-hep/pyhf/blob/8a3dc6b489c9a728bbf4994c25a63369100e9c40/.github/workflows/dependencies-head.yml) currently tests against the HEAD of `pyhf`'s core dependencies, but to try to catch things like `torch` `v0.10.0` breaking things _slightly_ (like in PR #1639, where PyTorch enabled zero rate Poisson support (c.f. PR #1657)) we can also test against all release candidates on PyPI with adding a run that turns on `--pre` in the `pip install`.

### Additional Information

The following addition should work

```yaml
jobs:
  release-candidates:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip --no-cache-dir --quiet install --upgrade --pre .[test]
        python -m pip list

    - name: Test with pytest
      run: |
        pytest -r sx --ignore tests/benchmarks/ --ignore tests/contrib --ignore tests/test_notebooks.py
```

### Code of Conduct

- [X] I agree to follow the Code of Conduct
