### ISSUE TITLE
Develop PatchSet JSON Schema

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#631]
# Description

distributing a tarball with O(100) files is a bit overwhelming. I think it would be better to define a patch set, which could just be 

```
[
  {
    "metadata": {
        "sbottom_mass": 100,
        "neutralino_mass": 300
    },
    "patch": [
        {"op": "replace"},
        {"op": "replace"}
    ]
  },
  {
    "metadata": {
        "sbottom_mass": 200,
        "neutralino_mass": 400
    },
    "patch": [
        {"op": "replace"},
        {"op": "replace"}
    ]
  }
]
```

to get a specific patch one could do:
```
cat patchset.json|ca|jq '.[]|select(
.metadata.sbottom_mass == 100 and \
.metadata.neutralino_mass == 300
).patch'
```
This way for example the sbottom hepdata tarball would only be 6 files

* RegionA/BkgOnly.json
* RegionA/SignalPatchSet.json
* RegionB/BkgOnly.json
* RegionB/SignalPatchSet.json
* RegionC/BkgOnly.json
* RegionC/SignalPatchSet.json

**Comment by kratsg** [comment]
here's a proposal for the hepdata yaml

```yaml
likelihoods:
- type: histfactory
  name: RegionA
  workspace:
    name: background-only
    description: background-only workspace
    $ref: BkgOnly.json
    $schema: https://scikit-hep.org/pyhf/schemas/1.0.0/workspace.json
  patchset:
    name: patchsets
    description: sets of signal patches for the background-only workspace
    $ref: patchset.json
    $schema: https://scikit-hep.org/pyhf/schemas/1.0.0/patchset.json
```

A few keypoints
- instead of inlining the workspaces and the patchsets (which can be obnoxiously large), we'll want `$ref` to resolve them and inline as this is parsed
- the `$schema` will point to the schema that the provided `$ref` should be validated against
- free-form metadata `name` and `description` are generally useful

Question:
- now that we've included `$schema` explicitly, should `type: histfactory` be dropped? is this perhaps a key/field that could be used to search for hepdata entries with a `histfactory` type?

**Comment by kratsg** [comment]
For the patchset, the following information should be stored:

- a checksum of the corresponding background-only workspace that the patchset was built against (`hashlib.md5(json.dumps(bkgonly, sort_keys=True)).hexdigest()`
- metadata at top level to describe patchset (point labels, description, analysis name, other?)
  ```
  patch: ...
  metadata:
      checksum: 1c60e7aff7adf44c2eb27a666598218e04bf2609
      labels: ["mass_stop","mass_neutralino"]
      description: signal patchset for the SUSY Multi-b-jet analysis
      analysis_id: SUSY-2018-23
  ```
- metadata for each patch to allow for filtering (name, point values, other?) [see CLI below for example usage]
  ```
  patch: ...
  metadata:
      name: Gtt_2100_5000_800
      points: [2100,800]
  ```
- should be a list of dictionaries
  ```
  patches:
    - {signal patch}
    - {signal patch}
    - {signal patch}
  ```

```
pyhf cls BkgOnly.json --patchset patchset.json --patch name=Gtt_2100_5000_800
pyhf cls BkgOnly.json --patchset patchset.json --patch mass=[2100,800]
```

For the schema itself, we should inline the patchset schema from http://json.schemastore.org/json-patch . There's a possible concern about licensing that needs to be cleared up.
